### ISSUE TITLE
Pip install may be broken?

### ISSUE THREAD

**Issue by iJebus** [wong2/pick#1]
Hey, I like the idea but I think there may be some issues with the pip installation. Pip successfully completes the install but `from pick import pick` is returning `ImportError: No module named 'pick'`. I'm using Python 3.4 via Anaconda. 

Cloning the repo, the test passes and when running Python from the repo directory, I'm able to import pick. Note that I can't run the basic.py example from the example folder, but it works when moved to the base directory.

So I'm fairly sure it must be an issue with the pip installer. I'm not all that familiar with python packaging otherwise I'd look into it more myself. Thanks for the repo and sorry in advance if I've missed something obvious.

```
pip show pick
---
Metadata-Version: 2.0
Name: pick
Version: 0.3.0
Summary: pick an option in the terminal with a simple GUI
Home-page: https://github.com/wong2/pick
Author: wong2
Author-email: wonderfuly@gmail.com
License: MIT
Location: /home/liam/anaconda3/lib/python3.4/site-packages
Requires: 
```
```
/pick-0.3.0.dist-info> ls
DESCRIPTION.rst  METADATA  metadata.json  pbr.json  RECORD  top_level.txt  WHEEL
```

**Comment by wong2** [comment]
Oh sorry, I made a mistake in `setup.py`. I've uploaded a new package, please update with pip and try again.

**Comment by iJebus** [comment]
Thanks, it's working for me now :)

**Comment by wong2** [comment]
@iJebus :beers:

**Comment by pjennings89012** [comment]
Hey there - just an FYI that I noticed this issue on Python 3.5 as well. Possibly because of no 3.5 classifer in setup.py, but that's just speculation on my part.

**Comment by wong2** [comment]
@pjennings89012 I tried with Python3.5 and can't produce this issue. still, I added 3.5 classifer in setup.py: https://github.com/wong2/pick/commit/3a554db7007513471adb8dd7859e5c0551550181

**Comment by pjennings89012** [comment]
@wong2 - working. Thanks.
