### ISSUE TITLE
Let the user write-in a choice.

### ISSUE THREAD

**Issue by aohanian** [wong2/pick#16]
This is an awesome package.   

What would it take to have an option to take user input if the right choice is not available?

**Comment by BigglesZX** [comment]
@aohanian I just found this library and haven't used it yet, but I imagine the most straightforward thing would be to provide an "other" choice, then if that is selected, request the user's custom choice with [`raw_input`](https://docs.python.org/2/library/functions.html#raw_input). I imagine you've probably solved this now, but there you go! :)
