### ISSUE TITLE
Several instances of picker

### ISSUE THREAD

**Issue by platx** [wong2/pick#24]
I got an issue with several instances of Picker class. 
For example:
```
first = Picker(['First 1', 'First 2'], 'Select first').start()
print(first)
second = Picker(['Second 1', 'Second 2'], 'Select second').start()
print(second)
```
After running this code i can choose just option in first picker, but not in second one. Let's say that i'm choosing option "First 2" with index 1. After i pressed enter, process finished and i got output:
> ('First 2', 1)
> ('Second 1', 0)
> 
> Process finished with exit code 0

But i didn't choose option from second picker.

Is it possible in some way to make several choices (for example, i have to choose category of commands, then command in selected category)?

**Comment by wong2** [comment]
your code works for me as expected, the second picker shows up after the first choice is made.
