### ISSUE TITLE
Using Pick with JSON

### ISSUE THREAD

**Issue by GiacomoLaw** [wong2/pick#26]
Trying to use Pip with this: https://raw.githubusercontent.com/GiacomoLaw/leaguestatistics/master/lib/serverlist.json

User sees `richname`, but variable is set to `server`. Thanks!

**Comment by GiacomoLaw** [comment]
Just was wondering if there was support for Json.

**Comment by wong2** [comment]
@GiacomoLaw no, the `options` must be a list of string

**Comment by GiacomoLaw** [comment]
Awesome, thanks.

**Comment by wong2** [comment]
Oh, I forgot this feature: https://github.com/wong2/pick#options-map-function should be what you need
