### ISSUE TITLE
tests part of pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [wong2/pick#28]
Hi,
could you please consider to add tests in the release, so they can be used in package checking?

**Comment by wong2** [comment]
I'm not sure, how is it working?

**Comment by lgbaldoni** [comment]
@wong2 the tests are still absent from the pypi release tarball and there is no corresponding 0.6.6 release or tag to download from github.

**Comment by wong2** [comment]
@lgbaldoni hi I've released v0.6.6

**Comment by lgbaldoni** [comment]
@wong2 it's nice to be able to run tests when packaging python modules for linux distributions, to make sure everything is ok.
