### ISSUE TITLE
Option to not return the index

### ISSUE THREAD

**Issue by verhovsky** [wong2/pick#33]
I'm using `multi_select=True` to chose from a long list of strings and I don't care about the index.

Right now I have to add a small list comprehension after every call to `pick`

```python
chosen = pick(['a', 'b'], multi_select=True)
chosen = [val for val, index in chosen]
```

it would be nicer if it could be an option instead of a whole line of code.

Also, I expected `multi_select` to be spelled without the underscore: `multiselect=True`.

**Comment by wong2** [comment]
I'd rather keep the API more general.
As with `multiselect`, you're right, I'll change it
