### ISSUE TITLE
Pick feature is not working in VScode terminal

### ISSUE THREAD

**Issue by shantanutheone** [wong2/pick#36]
Up or Down Arrow is not working in vscode terminal

**Comment by hartwork** [comment]
Does it work outside of VScode?

Just an idea: Does VScode have an option somewhere to enable VT emulation? Else, [is VT emulation enabled](https://stackoverflow.com/a/51681675/11626624) in general (system wide) for you?

**Comment by shantanutheone** [comment]
Yes, it does work outside of VScode and also I have enabled VT emulation from powershell of VScode but this doesn't work too.

**Comment by hartwork** [comment]
Which curses module for Python are you using on Windows?

**Comment by shantanutheone** [comment]
Not using any curses module. Should I be?

**Comment by hartwork** [comment]
Pick [uses curses](https://github.com/wong2/pick/blob/855864d954467cd43e72da06375db606b216eb4f/pick/__init__.py#L3) and the way I read #15 I assumed you installed some curses module manually at some point in the past — no?

**Comment by shantanutheone** [comment]
Yes yes now i remember the prerequisites of the pick module so i followed the readme and installed it like - `pip install windows-curses`

**Comment by wong2** [comment]
Does it work now?

**Comment by shantanutheone** [comment]
No ofcourse not, i was telling the answer of your question that how do i installed curses.

**Comment by hartwork** [comment]
@shantanutheone : @wong2 is not me/@hartwork :smile: 
@wong2: Nothing changed, we just gathered more information on the precise environment

**Comment by wong2** [comment]
ok I'll investigate it

**Comment by shantanutheone** [comment]
@wong2 Yes please check it by running it in VScode terminal. You'll know exactly what i'm talking about.

**Comment by wong2** [comment]
<img width="407" alt="截屏2020-08-16 下午12 30 18" src="https://user-images.githubusercontent.com/321947/90326567-58824700-dfbc-11ea-8b6f-56397c1146a9.png">

I tried and it works for me

**Comment by shantanutheone** [comment]
![del](https://user-images.githubusercontent.com/40365125/90326591-c3755300-dfa7-11ea-813b-52b3bddcd8ae.png)
Why there is an arrow in vscode terminal? That's means you have different setting in VScode. Ok then it looks like i have find the problem in my VScode terminal.

**Comment by shantanutheone** [comment]
Ok then I'll check my VScode terminal setting then.

**Comment by i30817** [comment]
I have this same problem (arrow keys not moving the cursor and printing) while trying to make my application work in windows (through wine).

Might not be worth it to you if it's a wine only problem although i'd prefer the peace of mind confirming that
![Screenshot from 2022-03-14 13-11-36](https://user-images.githubusercontent.com/757900/158178728-ad6831ad-c659-43a6-8c0b-a0d089659d6a.png)
