### ISSUE TITLE
Support for initial selection?

### ISSUE THREAD

**Issue by hartwork** [wong2/pick#37]
Hi, thanks for sharing `pick` as software libre! :pray: 

In my scenario I need to pre-select some options, primarily for multi-select mode. [What I currently do](https://github.com/hartwork/git-delete-merged-branches/blob/04fdeb4eec4223d03af387e183baa7d50e6b3607/git_delete_merged_branches/_multiselect.py#L7-L16) at [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) is this:

```python
from pick import Picker

class _PickerWithPreselection(Picker):
    def __init__(self, options, initial_selection=None, **kwargs):
        super().__init__(options, **kwargs)
        if initial_selection is not None:
            self.all_selected = sorted(
                set(i for i in initial_selection if isinstance(i, int) and 0 <= i < len(options)))
            if self.all_selected and kwargs.get('default_index') is None:
                self.index = self.all_selected[0]
```

Is that something you'd want to integrate with `pick`?

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by wong2** [comment]
Yeah PR is welcomed

**Comment by hartwork** [comment]
Closing due to https://github.com/wong2/pick/pull/38#issuecomment-783307416
