### ISSUE TITLE
Trouble running it on MacOS using PyCharm

### ISSUE THREAD

**Issue by thevickypedia** [wong2/pick#49]
I tried running it on MacOS using PyCharm, tried to replicate your example:
```
from pick import pick
title = 'Please choose your favorite programming language: '
options = ['Java', 'JavaScript', 'Python', 'PHP', 'C++', 'Erlang', 'Haskell']
option, index = pick(options, title, indicator='=>', default_index=2)
print(option, index)
```
I keep getting the `_curses.error: nocbreak() returned ERR` exception. I tried the solution [here](https://stackoverflow.com/a/57535960) still no luck. Is there any chance I can have this working on PyCharm output console instead of a Terminal?

**Comment by emeryjune** [comment]
@thevickypedia The error is because it doesn't identify the Pycharm console as an actual terminal. You can fix this by going to Edit Configuration (top right corner, left from the Play/Run button). Then check Execution => Emulate terminal in output console

**Comment by thevickypedia** [comment]
works like a charm, thank you @emeryjune :)
![Screen Shot 2021-02-15 at 12 23 25 PM](https://user-images.githubusercontent.com/38729644/107981887-9fabbd80-6f88-11eb-93ea-a321c4ff5c16.png)
