### ISSUE TITLE
windows issues

### ISSUE THREAD

**Issue by mtrzcinski** [wong2/pick#5]
I does not work on Windows systems. Curses module is not included in windows python distribution.
https://docs.python.org/3.3/howto/curses.html

**Comment by wong2** [comment]
hmm, I don't have a Windows system, the doc mentioned [UniCurses](https://pypi.python.org/pypi/UniCurses), if you're interested you can try to include it in pick

**Comment by wong2** [comment]
seems windows users can install curses from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses

**Comment by hartwork** [comment]
Related: #15
