### ISSUE TITLE
Anyway to not do screen clear?

### ISSUE THREAD

**Issue by juandiegopalomino** [wong2/pick#50]
I'm trying to offer a helpful description rendered with rich and then having options on how to proceed at the bottom with pick

**Comment by juandiegopalomino** [comment]
I managed to get it to work by capturing the rich output, and passing it as the title but it can't seem to render unicode.

**Comment by wong2** [comment]
Can you show some code here?

**Comment by pranjal-joshi** [comment]
I want to append the Prompt without clearing the existing data on the screen. How to do it @wong2 ?

**Comment by idoo** [comment]
that would be awesome to have :)

**Comment by DystDev** [comment]
Any info on this?

**Comment by manuelfuchs** [comment]
@wong2 any updates on this? I am happy to help if needed.

**Comment by wong2** [comment]
PRs are always welcome!

**Comment by wong2** [comment]
After some research, I have to say this is technically hard (if not impossible) to do, `curses` is designed to clear the screen. So I will close this issue for now.

**Comment by Cornelius-Figgle** [comment]
I have embedded `pick` into a `curses` window, passing the window object, but yet it still clears my curses content when I call `pick`. Is their anyway around this?
