### ISSUE TITLE
Enter key on the numeric keypad ?

### ISSUE THREAD

**Issue by hunshcn** [wong2/pick#53]
I'm very lucky to find this library, but i found the enter key on the numeric keypad cannot take effect. This code is 459.
Is it a feature? Maybe can make it optional or add a action key map

**Comment by wong2** [comment]
Is 459 the code of your numpad enter key?

**Comment by hunshcn** [comment]
Yes

2021-11-29 13:57 GMT+08:00, Wang Dàpéng ***@***.***>:

**Comment by wong2** [comment]
It doesn't seem like a universal code, can't get reasonable result googling it.
