### ISSUE TITLE
1.0.0 has been overwritten and broken

### ISSUE THREAD

**Issue by gregersn** [wong2/pick#60]
From the files list on PyPi it shows that the wheel file for python 3, 1.0.0. was uploaded 2021-12-04, which probably introduced the screen-parameter bug into older version, breaking installs also for people with locked version for older releases.

This should not happen, as it leads to a massive amount of confusion.

https://pypi.org/project/pick/1.0.0/#files

**Comment by wong2** [comment]
Hi I've deleted the wheel file, really sorry for the mistake
