### ISSUE TITLE
kernel restart when "option, index = pick(options, title)"

### ISSUE THREAD

**Issue by Pertii** [wong2/pick#64]
I'm new to Python, i don't know why this code "option, index = pick(options, title)" make my kernel reboot. I've installed pick by "pip install pick" and i imported it correctly with "from pick import pick". I'm working on anaconda on win11.

This is the full code

```
from pick import pick

title = 'Please choose filter: '
options = ['trending', 'hot', 'created', 'promoted']
option, index = pick(options, title)
```

**Comment by wong2** [comment]
I have no idea because I don't have a windows computer. Can you still reproduce this?

**Comment by wong2** [comment]
@InvisibleWaves according to a comment in https://stackoverflow.com/questions/70084286/lines-value-must-be-2-and-168-got-1-initscr-unable-to-create-sp 

> curses is generally not going to work from within an IDE - try running it directly from a terminal window.

**Comment by wong2** [comment]
Close as IDE terminals are not supported.
