### ISSUE TITLE
Pick for trees - Pull request?

### ISSUE THREAD

**Issue by anafvana** [wong2/pick#65]
So... I needed pick for tree structures. So I made the necessary changes. And then I made some more.

It was supposed to be just a small pull request, but it turned into a project of its own, so here is my question: would you like me to make [my fork](https://github.com/anafvana/pickpack) into a pull request?

I've released it as its own package for now, because I needed it up for the project that originated it all, but I'll be happy to contribute upstream! I just don't know if it's too far from the original scope of your project at this point.

In any case, thank you so much for this picker! Your code saved me a lot of trouble and time.

**Comment by wong2** [comment]
Hi anafvana, your fork looks powerful indeed! However, it seems out of the scope of `pick`, a simple library to select from a list of data. So I'd suggest not integrating tree selecting in this repo. But I'd be happy to add a link to your project in README

**Comment by anafvana** [comment]
Then we leave them unmerged and I leave my huge thanks to you for giving me the basis for pickpack!

And if you want to link to the tree version in your README, I will be grateful for the free advertisement! (Although you are not in any way obliged to do it)

**Comment by wong2** [comment]
Yeah I've added it. https://github.com/wong2/pick#community-projects=

**Comment by wong2** [comment]
Nice job!
