### ISSUE TITLE
Problem when trying to use colorama Colors in title

### ISSUE THREAD

**Issue by Epic-Fox-1234** [wong2/pick#70]
When trying to use colors in the title it doesn't show the colors and instead showing the color code i guess
![Screenshot 2022-08-14 160619](https://user-images.githubusercontent.com/96354142/184540743-198ade34-a9db-41e5-a103-685a30df1b2f.jpg)

**Comment by wong2** [comment]
It doesn't support colorama. PR welcomed

**Comment by wong2** [comment]
Dup of https://github.com/wong2/pick/issues/70
