### ISSUE TITLE
_curses.error: addstr() returned ERR

### ISSUE THREAD

**Issue by manuel-delverme** [wong2/pick#8]
Traceback (most recent call last):
  File "extract.py", line 19, in <module>
    style, _ = pick(sorted(list(styles)), title)
  File "/usr/local/lib/python2.7/dist-packages/pick/__init__.py", line 148, in pick
    return picker.start()
  File "/usr/local/lib/python2.7/dist-packages/pick/__init__.py", line 134, in start
    return curses.wrapper(self._start)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pick/__init__.py", line 131, in _start
    return self.run_loop()
  File "/usr/local/lib/python2.7/dist-packages/pick/__init__.py", line 109, in run_loop
    self.draw()
  File "/usr/local/lib/python2.7/dist-packages/pick/__init__.py", line 102, in draw
    self.screen.addstr(y, x, line)
_curses.error: addstr() returned ERR

changing row 102 from:
102             self.screen.addstr(y, x, line)
to:
102             self.screen.addstr(y - 1, x, line)

avoids the error.. but i'm not sure about what i'm really doing here..

might be related to:
#2 

pick version:
➜  /tmp sudo pip show pick
---
Metadata-Version: 2.0
Name: pick
Version: 0.6.0
Summary: pick an option in the terminal with a simple GUI
Home-page: https://github.com/wong2/pick
Author: wong2
Author-email: wonderfuly@gmail.com
Installer: pip
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5

**Comment by wong2** [comment]
@manuel-delverme how can I reproduce this?

**Comment by manuel-delverme** [comment]
this is the script
https://github.com/manuel-delverme/scripts/blob/master/radio.py

you can ignore both os.execv and pyfscache
the problem happens on the first pick()

**Comment by wong2** [comment]
@manuel-delverme does it work if you increase the width of the terminal?

**Comment by manuel-delverme** [comment]
yea,
try this script
https://gist.github.com/manuel-delverme/9dea5813fc9a9601b210f31bac6f8e55

**Comment by wong2** [comment]
please try v0.6.1
