### ISSUE TITLE
RFE: Document Pick methods

### ISSUE THREAD

**Issue by devwatchdog** [wong2/pick#81]
Would you please document the methods in Pick?

As it is currently, it is a guess game what the various methods actually do. Well, move_up() and move_down() can be guessed
correctly, but register_custom_handler(), get_option_lines(), get_lines() etc. might not be guessed easily.
I would to suggest to mark those methods as private if you don't want them to be used from outside.

Thanks by the way for writing the library.

**Comment by wong2** [comment]
Hi, `register_custom_handler` have been removed recently. Other methods you mentioned are not intended to be used outside.
