### ISSUE TITLE
Windows not working

### ISSUE THREAD

**Issue by Pukimaa** [wong2/pick#84]
I am using the latest Windows 10 Pro version and when I run a script using pick it won't let me switch between the choices. It always stays on the first option. On Linux everything works fine.

**Comment by laundmo** [comment]
Are you in VSCode? For me, it only worked when using Windows Terminal, the VSCode terminal didn't work.

**Comment by wong2** [comment]
Hi @Pukimaa can you confirm this?

**Comment by riccardogabellone** [comment]
For me, in Windows 11, works both in VSCode terminal and in Windows Terminal

**Comment by Pukimaa** [comment]
I can confirm that it works with both Powershell and CMD if not used in VSCode
