### ISSUE TITLE
Can it support other language?

### ISSUE THREAD

**Issue by Shimon-Guo** [wong2/pick#93]
Can it support other language?

**Comment by wong2** [comment]
Have you met some problem?

**Comment by Shimon-Guo** [comment]
The menu bar cannot display Chinese correctly

**Comment by Shimon-Guo** [comment]
> Can you test it in a real terminal? Not the one included by IDE

Real terminal is the same, I use the Ubuntu16.04

![image](https://user-images.githubusercontent.com/33592567/203238661-9a6b99ee-8d41-418a-a86b-51de41769f1a.png)

**Comment by Shimon-Guo** [comment]
I use another pc(Ubuntu 16.04) , it display ok, maybe my env is error, I will check it again.

**Comment by wong2** [comment]
Yeah, please check out your font config

**Comment by Shimon-Guo** [comment]
> 

The problem lies in the version of python compiled by myself. I changed a python version and the problem was solved

**Comment by wong2** [comment]
Great!
